languageCode = 'de-de'
title = 'pages.beno.de'
Params.description = 'Test-Website des Autors Benno Kieselstein'
Params.author = 'Benno Kieselstein'
Params.email = 'pages@beno.de'
Params.version = 'Version 0.1.0, 2025-04-15'
copyright = 'Benno Kieselstein 2025'
theme = 'hugo-story/'
disableKinds = ["taxonomy"]
sectionPagesMenu = "main"
favicon = true
[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[module]
  [module.imports]
    path = 'github.com/caressofsteel/hugo-story'
